
import { ForestRecord, IndustryRecord, CommerceRecord, Role, User } from './types';

export const mockForestData: ForestRecord[] = [
  {
    id: 'F1',
    sn: '001',
    office: 'डिभिजन वन कार्यालय, चितवन',
    date: '2024-05-20',
    current_allocation: 5000000,
    capital_allocation: 2000000,
    current_expenditure: 3500000,
    capital_expenditure: 1200000,
    financial_progress_pct: 67,
    community_forest_count: 85,
    religious_forest_count: 4,
    leasehold_forest_count: 12,
    total_forest_area: 12500.5,
    revenue: 1500000,
    audit_settlement: 200000,
    arrears_recoverable: 50000,
    arrears_regularizable: 150000,
    advance_arrears: 10000,
    timber_production: 4500,
    cases_filed: 2,
    workplan_renewal: 5,
    workplan_registration: 3,
    saplings: 25000,
    herbs: 1200,
    resin: 450,
    plantation: 15,
    approved_positions: 45,
    filled_positions: 42,
    physical_progress: 'अति राम्रो',
    cf_area: 8500,
    lf_area: 1200,
    rf_area: 300,
    cf_hh: 4500,
    lf_hh: 120,
    rf_hh: 15,
    encroachment: 5,
    relief: 250000,
    status: 'Approved',
    createdBy: 'ENUM1'
  }
];

export const mockIndustryData: IndustryRecord[] = [
  {
    id: 'I1',
    office: 'घरेलु तथा साना उद्योग कार्यालय, काठमाडौं',
    month: 'बैशाख',
    current_allocation: 4500000,
    capital_allocation: 1500000,
    current_expenditure: 2100000,
    capital_expenditure: 400000,
    financial_progress_pct: 42,
    reg_count: 120,
    renewal_count: 450,
    loc_transfer_count: 12,
    name_change_count: 8,
    copy_count: 5,
    amend_count: 15,
    cancel_count: 3,
    owner_transfer_count: 7,
    cap_increase_count: 22,
    other_count: 10,
    micro_count: 45,
    cottage_count: 30,
    small_count: 35,
    medium_count: 8,
    large_count: 2,
    energy_count: 5,
    production_count: 40,
    agro_forest_count: 25,
    service_count: 30,
    tourism_count: 15,
    mineral_count: 1,
    infra_count: 2,
    it_count: 2,
    female_emp: 450,
    male_emp: 680,
    reg_rev: 120000,
    renewal_rev: 450000,
    loc_transfer_rev: 12000,
    name_change_rev: 8000,
    copy_rev: 2500,
    amend_rev: 7500,
    cancel_rev: 1500,
    owner_transfer_rev: 14000,
    cap_increase_rev: 44000,
    other_rev: 5000,
    total_rev: 664500,
    approved_pos: 24,
    filled_pos: 21,
    total_industries: 1250,
    verificationStatus: 'Approved',
    createdBy: 'ENUM1'
  }
];

export const mockCommerceData: CommerceRecord[] = [
  {
    id: 'C1',
    office: 'घरेलु तथा साना उद्योग कार्यालय, भक्तपुर',
    month: 'जेठ',
    comm_reg: 85,
    renewal: 210,
    cap_increase: 15,
    copy: 4,
    owner_transfer: 6,
    loc_transfer: 2,
    amendment: 9,
    cancellation: 1,
    details: 'वाणिज्य क्षेत्रको नियमित प्रगति विवरण।',
    cap_increase_amt: 12500,
    other: 5,
    reg_rev: 95000,
    other_rev: 12000,
    total_rev: 107000,
    total_comm_reg: 850,
    status: 'Approved',
    createdBy: 'ENUM1'
  }
];

export const USERS: User[] = [
  { id: '1', name: 'Super Admin', email: 'super@mitfe.gov.np', role: Role.SUPER_ADMIN, department: 'General' },
  { id: '2', name: 'Forest Admin', email: 'forest@mitfe.gov.np', role: Role.ADMIN, department: 'Forest' },
  { id: '3', name: 'Industry Admin', email: 'industry@mitfe.gov.np', role: Role.ADMIN, department: 'Industry' },
  { id: '4', name: 'Hari Prasad', email: 'hari@mitfe.gov.np', role: Role.ENUMERATOR, department: 'Forest' },
  { id: '5', name: 'Sita Devi', email: 'sita@mitfe.gov.np', role: Role.VIEWER, department: 'General' },
];
